import React, { useState } from 'react';
import { Upload, Camera, AlertCircle, CheckCircle2, Loader2, ArrowRight, FileText, XCircle } from 'lucide-react';
import { motion as Motion } from 'framer-motion';
import { useAuth } from '../context/AuthContext';
import API_URL from '../config';
import '../styles/PatientDashboard.css';
import { validateIsSkinImage } from '../utils/imageValidator';

const PatientDashboard = () => {
  const { user, logout } = useAuth();
  const [image, setImage] = useState(null);
  const [analyzing, setAnalyzing] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [showHeatmap, setShowHeatmap] = useState(false);
  const [heatmapPos] = useState({ t: '30%', l: '40%' });

  const handleImageUpload = (e) => {
    const file = e.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setImage(reader.result);
        setResult(null);
        setError(null);
        setShowHeatmap(false);
      };
      reader.readAsDataURL(file);
    }
  };

  const [processingStage, setProcessingStage] = useState('');

  const analyzeSkin = async () => {
    if (!image) return;
    setAnalyzing(true);
    setError(null);
    setResult(null);

    // Pseudo-CNN UI Stages (Updated for Clinical Markers)
    const stages = [
      { name: 'Decomposing RGB to LAB Color Space...', delay: 700 },
      { name: 'Calculating Contour Asymmetry & Border Irregularity...', delay: 1200, action: () => setShowHeatmap(true) },
      { name: 'Running Multi-Scale Texture Scaling Detection...', delay: 1000 },
      { name: 'Scanning for Erythematous Blobs & Papules...', delay: 900 }
    ];

    // 1. Basic Validation (Keep for speed)
    const validation = await validateIsSkinImage(image);
    if (!validation.isValid) {
      setAnalyzing(false);
      setError("AI Input Error: Grad-CAM failed to localize skin. Please re-take the photo.");
      return;
    }

    // 2. UI Animation Sequence
    let currentDelay = 0;
    stages.forEach((stage) => {
      setTimeout(() => setProcessingStage(stage.name), currentDelay);
      currentDelay += stage.delay;
    });

    // 3. Real AI Analysis (Run in parallel with UI)
    try {
      const response = await fetch(`${API_URL}/api/analyze`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ image })
      });

      const data = await response.json();
      if (!response.ok) throw new Error(data.message || 'AI Analysis failed');

      // Final result after UI animation finishes
      setTimeout(() => {
        setAnalyzing(false);
        setResult({
          id: "AI-" + Math.floor(Math.random() * 10000),
          model: "TensorFlow-CNN-v4",
          date: new Date().toLocaleDateString(),
          condition: data.condition,
          confidence: data.confidence,
          allScores: data.all_scores,
          severity: ["Malignant Melanoma", "Basal Cell Carcinoma", "Squamous Cell Carcinoma"].includes(data.condition) ? "Critical"
            : data.condition === "Healthy Skin" ? "Normal" : "Moderate",
          recommendation: ["Malignant Melanoma", "Basal Cell Carcinoma", "Squamous Cell Carcinoma"].includes(data.condition)
            ? "Urgent clinical evaluation required. Patterns match malignant markers."
            : data.condition === "Healthy Skin"
              ? "No significant pathological markers detected. Maintain skin hydration."
              : `AI detected ${data.condition} markers. Consultation recommended.`,
          riskLevel: ["Malignant Melanoma", "Basal Cell Carcinoma", "Squamous Cell Carcinoma"].includes(data.condition) ? "critical"
            : data.condition === "Healthy Skin" ? "low" : "medium",
          progression: data.progression
        });
      }, currentDelay);

    } catch (err) {
      setAnalyzing(false);
      setError("Medical AI Error: " + err.message);
    }
  };

  const downloadReport = () => {
    if (!result) return;
    const reportText = `
-----------------------------------------
      SKINDL AI MEDICAL REPORT
-----------------------------------------
Report ID: ${result.id}
Model: ${result.model} (CNN Architecture)
Date: ${result.date}
Patient Name: ${user?.name || 'Anonymous'}

FINDINGS:
Condition: ${result.condition}
Inference Confidence: ${result.confidence}
Pattern Severity: ${result.severity}

RECOMMENDATION:
${result.recommendation}

Disclaimer: This report is generated by an AI assistant and should not be considered a final clinical diagnosis.
-----------------------------------------
    `;
    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `SkinDL_Report_${result.id}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="dashboard-container">
      <header className="dash-header glass">
        <div className="user-info">
          <div className="avatar">{user?.name?.charAt(0) || 'P'}</div>
          <div>
            <h3>Welcome, {user?.name || 'Patient'}</h3>
            <span className="badge">Verified Patient</span>
          </div>
        </div>
        <button className="logout-btn" onClick={logout}>Logout</button>
      </header>

      <main className="dash-main">
        <section className="detector-section">
          <div className="section-header">
            <h2>Skin Disease Detector</h2>
            <p>Upload a clear photo of the skin concern for instant AI analysis.</p>
          </div>

          <div className="detector-grid">
            <div className="upload-box glass">
              {!image ? (
                <label className="upload-label">
                  <Upload size={48} color="var(--primary)" />
                  <span>Click to upload or drag & drop</span>
                  <small>PNG, JPG up to 10MB</small>
                  <input type="file" accept="image/*" onChange={handleImageUpload} hidden />
                </label>
              ) : (
                <div className="preview-container">
                  <img src={image} alt="Preview" className="image-preview" />
                  {showHeatmap && (
                    <div className="heatmap-overlay">
                      <div className="heatmap-blob hb1" style={{ top: heatmapPos.t, left: heatmapPos.l }}></div>
                      <div className="heatmap-blob hb2" style={{ top: `calc(${heatmapPos.t} + 20px)`, left: `calc(${heatmapPos.l} - 30px)` }}></div>
                      <div className="heatmap-blob hb3" style={{ top: `calc(${heatmapPos.t} - 40px)`, left: `calc(${heatmapPos.l} + 50px)` }}></div>
                      <div className="heatmap-label">Grad-CAM Activation Map</div>
                    </div>
                  )}
                  <button className="change-btn" onClick={() => setImage(null)}>Change Image</button>
                </div>
              )}
            </div>

            <div className="analysis-box glass">
              {!image ? (
                <div className="empty-state">
                  <Camera size={40} className="muted-icon" />
                  <p>Upload an image to start analysis</p>
                </div>
              ) : analyzing ? (
                <div className="analyzing-state">
                  <div className="cnn-visualizer">
                    <Loader2 className="spinner" size={48} color="var(--primary)" />
                    <div className="nn-nodes">
                      <span className="node"></span>
                      <span className="node"></span>
                      <span className="node"></span>
                    </div>
                  </div>
                  <h3>{processingStage || 'Initializing CNN...'}</h3>
                  <p>Running Convolutional Neural Network inference.</p>
                  <div className="progress-bar">
                    <Motion.div
                      className="progress-fill"
                      initial={{ width: 0 }}
                      animate={{ width: "100%" }}
                      transition={{ duration: 3 }}
                    />
                  </div>
                </div>
              ) : error ? (
                <Motion.div
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  className="error-state"
                >
                  <XCircle size={48} color="#ef4444" />
                  <h3>Image Rejected</h3>
                  <p>{error}</p>
                  <button className="change-btn-static" onClick={() => { setImage(null); setError(null); }}>
                    Try Different Image
                  </button>
                </Motion.div>
              ) : result ? (
                <Motion.div
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  className="result-card"
                >
                  <div className={`result-header ${result.riskLevel}`}>
                    <AlertCircle size={24} />
                    <span>{result.condition}</span>
                  </div>

                  <div className="result-stats">
                    <div className="stat">
                      <span className="label">Confidence</span>
                      <span className="value">{result.confidence}</span>
                    </div>
                    <div className="stat">
                      <span className="label">Severity</span>
                      <span className="value">{result.severity}</span>
                    </div>
                  </div>

                  <div className="recommendation">
                    <h4>Recommendation:</h4>
                    <p>{result.recommendation}</p>
                  </div>



                  {result.progression && (
                    <div className="progression-analysis">
                      <h4>Time-Series Progression Forecast</h4>
                      <div className="progression-grid">
                        <div className="progression-item">
                          <span className="p-time">Timeline: +3 Months</span>
                          <p className="p-desc">{result.progression['3_months']}</p>
                        </div>
                        <div className="progression-item">
                          <span className="p-time">Timeline: +6 Months</span>
                          <p className="p-desc">{result.progression['6_months']}</p>
                        </div>
                      </div>
                    </div>
                  )}

                  <div className="xai-diagnostic">
                    <div className="xai-header">
                      <h4>Explainable AI (XAI) Diagnostic</h4>
                      <button
                        className={`xai-toggle ${showHeatmap ? 'active' : ''}`}
                        onClick={() => setShowHeatmap(!showHeatmap)}
                      >
                        {showHeatmap ? 'Hide Feature Map' : 'View Feature Map (Grad-CAM)'}
                      </button>
                    </div>
                    <p className="xai-desc">
                      The CNN is focusing on <strong>spatial textures</strong> rather than lesion borders.
                      {result.condition === 'Atopic Dermatitis (Eczema)' && ' High reflection in the center might be causing the model to misinterpret vascular patterns as inflammatory eczema markers.'}
                    </p>
                  </div>

                  <div className="result-actions">
                    <button className="action-btn download" onClick={downloadReport}>
                      <FileText size={18} /> Download Report
                    </button>
                    <button className="action-btn">
                      Consult Dermatologist <ArrowRight size={18} />
                    </button>
                  </div>
                </Motion.div>
              ) : (
                <div className="ready-state">
                  <CheckCircle2 size={48} color="var(--primary)" />
                  <h3>Image Ready</h3>
                  <p>The image is clear and ready for scanning.</p>
                  <button className="analyze-btn" onClick={analyzeSkin}>
                    Run AI Analysis
                  </button>
                </div>
              )}
            </div>
          </div>
        </section>

        <aside className="recent-history">
          <h3>Recent Scans</h3>
          <div className="history-list">
            <div className="history-item glass">
              <div className="h-dot"></div>
              <div className="h-info">
                <strong>Acne Vulgaris</strong>
                <span>2 days ago • Mild</span>
              </div>
            </div>
            <div className="history-item glass">
              <div className="h-dot warning"></div>
              <div className="h-info">
                <strong>Psoriasis</strong>
                <span>1 week ago • High</span>
              </div>
            </div>
          </div>
        </aside>
      </main>
    </div >
  );
};

export default PatientDashboard;
